package com.company.projectEuler;

/**
 Problem 2
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */
public class Problem2 {
    public Problem2() {
        int currentFibNumber = 1;
        int previousFib = 1;
        int tempFib;
        int sum = 0;

        while (currentFibNumber < 4000000) {
            tempFib = currentFibNumber;
            currentFibNumber = currentFibNumber + previousFib;
            previousFib = tempFib;
            if((currentFibNumber % 2) == 0) {
                sum = sum + currentFibNumber;
            }
        }
        System.out.println( Integer.toString(sum));
    }
}
